### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by mehgcap**
This is my first-ever pull request, so apologies for what I do wrong. 

This branch adds just one feature: a setting to control the percentage a CPU core must be at before it is spoken. For instance, at the default of 1.0%, the list of core loads will skip any core at or under 1.0% load. On systems with a lot of cores, this can reduce the time needed to hear which cores are active, as ones at or near idle won't be output.

The branch also, of course, adds the code needed to handle settings in general. I have more plans for settings, and now that the basics are in place, the rest should be easier.

Please note that I have no idea how this addon's settings screen appears visually. I just know it works.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Can you resolve conflicts first? I think you added things while not pulling in latest Flake8 edit changes from mine.

Thanks.

**Comment by mehgcap** [comment]
No problem, but what's the best way? The web UI doesn't seem to work that well. Should I merge settings into master? Rebase settings on master? Something else? I've just pulled your master branch, updating mine to it. I'm just not sure what the protocol is where I'm doing the pull request.

**Comment by josephsl** [comment]
Hi, normally a merge is okay, but for this one, I recommend a rebase and push first, and if it doesn’t work, do a merge and then a push. Thanks.

**Comment by josephsl** [comment]
Hi,

No rebase nor merge is possible due to conflicts, and it appears the latest master you had was from May. I'll try cherry-pick instead.

Thanks.

**Comment by josephsl** [comment]
Hi,

Nope - cherry-pick fails with the very last commit from this branch, as the CPU core load output algorithm is vastly different between what I have now (list comprehension) versus the PR (traditional pull request). But I know what the PR does so I'll be able to review and do something about it.

Thanks.

**Comment by josephsl** [comment]
Hi,

I'll merge latest master and push it to your repo.

**Comment by josephsl** [comment]
Hi,

Actually, I recommend calling the config key "resourceMonitor" rather than "addons.resourceMonitor" and spell it out when looking up config key i.e. config.conf["resourceMonitor"][whatever]. I know that this is verbose but it saves us from having to hold onto a constant. This also applies to settings dialog title and such.

In regards to the core load loop, although I'll take care of it, it might be preferable to use enumerate() function as it gives us both the core number/position and core load, along with stylistic changes such as:

for something in range(range)

versus

for something in someContainer

The latter is more pythonic and allows us to work directly with the thing in question, not the index.

Thanks.

**Comment by mehgcap** [comment]
As to the key, I'm never comfortable using strings when I can use constants. One missed shift key, or misplaced letter, and things can fail. Plus, if the key ever has to change for some reason, it's one change instead of hoping a find/replace catches everything. I prefixed it with "addon." as a kind of namespace, to avoid conflicting with anything NVDA core does, though I don't know if that's entirely necessary.

I haven't looked at your latest changes yet, about the use of comprehensions and such, but I will tomorrow or Thursday. Is there anything more you want me to do?

**Comment by josephsl** [comment]
Hi, makes sense, although for consistency, I think it would be best to call it “resourceMonitor” to align with other add-ons. There’s really no standard as to how sections should be named apart from using camel case. I’ve already resolved conflicts and pushed changes to your repo. One important thing you may wish to address is that the setting has no label, which can be resolved by using labeled control part of gui.guiHelper. Thanks.

**Comment by josephsl** [comment]
Hi,

A very important thing to think about: if we're talking about CPU core load as a percentage, why is that the label for this setting says "GhZ"? I think it might be better to talk about load percentage somehow.

Thanks.

**Comment by mehgcap** [comment]
I'll change the tag.

Yes, using GhZ is a mistake; I'll fix that. I'll also see about a label.

I didn't realize you could push changes to the branch in my repo. Now I see where you made fixes.

**Comment by josephsl** [comment]
Hi, don’t worry about the for loop and list comprehension mess – I’ll take care of it once the PR is merged (with explanations added). Thanks.

**Comment by josephsl** [comment]
Hi,

2023 update: as Resource Monitor is end of life from me, this PR will be closed as EOL. Thanks.

**Pull request closed without merging**
